title: "Perseverance Makurira"
description: "Digital Marketing Strategist | AI Enthusiast | Creator"
baseurl: "" 
url: "https://perseverancemakurira.github.io"
theme: minima

plugins:
  - jekyll-feed

